apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: "2020-04-15T18:34:03Z"
  name: default
  namespace: default
  resourceVersion: "333"
  selfLink: /api/v1/namespaces/default/serviceaccounts/default
  uid: 7976adba-fdc6-4441-b4a7-4e564480b311
secrets:
- name: default-token-fbsd2